export function getVideoAulas() {
  return [
    {
      id: 1,
      titulo: 'Sistema de Equações - Introdução',
      videoId: 'o096RRiCRrM',
    },
    {
      id: 2,
      titulo:
        'Sistema de Equações - Método de Substituição',
      videoId: '7Pq9xXiDpro',
    },
    {
      id: 3,
      titulo: 'Sistema de Equações - Método de Substituição com Exemplo',
      videoId: '2fJ0UfxYEOY',
    },
    {
      id: 4,
      titulo: 'Sistemas de Equações - Método de Adição',
      videoId: 'GTgZFABrzpM',
    },
    {
      id: 5,
      titulo: 'Sistema de Equações - Método de Adição com Exemplo',
      videoId: 'cWmnhgLqO7w',
    },
  ];
}

export const getNivelAprendizado = perc => {
  return escalaAprendizado.find(nivel => {
    return perc >= nivel.criterio[0] && perc <= nivel.criterio[1];
  });
};

const escalaAprendizado = [
  {
    nivel: 'Novato dos Sistemas',
    criterio: [0, 12],
    descricao: 'Você está começando a entender o conceito de sistemas de equações. Continue praticando!',
  },
  {
    nivel: 'Resolutor de Substituições',
    criterio: [13, 18],
    descricao: 'Você já sabe como aplicar o método da substituição. Continue desafiando-se!',
  },
  {
    nivel: 'Mestre das Igualdades',
    criterio: [19, 24],
    descricao: 'Excelente! Você já domina os métodos de substituição e redução. Está pronto para sistemas mais complexos.',
  },
  {
    nivel: 'Perito em Sistemas Lineares',
    criterio: [25, 27],
    descricao: 'Você já é um especialista! Resolve sistemas com facilidade e precisão.',
  },
  {
    nivel: 'Lenda dos Sistemas de Equações',
    criterio: [28, 30],
    descricao: 'Você é uma lenda no domínio dos sistemas de equações! Parabéns pelo desempenho excepcional.',
  },
];


export const exerciciosInicial = [
  {
    id: 1,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\nx + y = 6\nx − y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 2', correta: true },
      { id: 'b', texto: 'x = 5, y = 1', correta: false },
      { id: 'c', texto: 'x = 3, y = 3', correta: false },
      { id: 'd', texto: 'x = 2, y = 4', correta: false },
    ],
    explicacao: 'Substitua y por x-2 em uma das equações para encontrar os valores.',
    feedback: {
      mensagens: {
        acerto: 'Parabéns, você acertou!',
        erro: 'Reveja os passos da substituição para resolver o sistema.',
      },
    },
  },
  {
    id: 2,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n2x + y = 10\nx − y = 4',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 6', correta: false },
      { id: 'b', texto: 'x = 5, y = 0', correta: true },
      { id: 'c', texto: 'x = 4, y = 2', correta: false },
      { id: 'd', texto: 'x = 3, y = 1', correta: false },
    ],
    explicacao: 'Some as equações para eliminar y e resolver para x.',
    feedback: {
      mensagens: {
        acerto: 'Ótimo trabalho!',
        erro: 'Tente somar as equações corretamente.',
      },
    },
  },
  {
    id: 3,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\nx − y = 1\nx + y = 9',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 5', correta: true },
      { id: 'b', texto: 'x = 5, y = 4', correta: false },
      { id: 'c', texto: 'x = 6, y = 3', correta: false },
      { id: 'd', texto: 'x = 7, y = 2', correta: false },
    ],
    explicacao: 'Substitua y = x - 1 na segunda equação para resolver o sistema.',
    feedback: {
      mensagens: {
        acerto: 'Muito bem!',
        erro: 'Revise a substituição de y.',
      },
    },
  },
  {
    id: 4,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n3x + y = 12\nx − y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 0', correta: true },
      { id: 'b', texto: 'x = 5, y = −1', correta: false },
      { id: 'c', texto: 'x = 3, y = 3', correta: false },
      { id: 'd', texto: 'x = 6, y = −2', correta: false },
    ],
    explicacao: 'Some as equações para eliminar y e encontrar x.',
    feedback: {
      mensagens: {
        acerto: 'Muito bom!',
        erro: 'Confira o somatório das equações.',
      },
    },
  },

  {
    id: 5,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n2x − y = 4\nx + y = 6',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 3', correta: false },
      { id: 'b', texto: 'x = 4, y = 2', correta: true },
      { id: 'c', texto: 'x = 5, y = 1', correta: false },
      { id: 'd', texto: 'x = 2, y = 4', correta: false },
    ],
    explicacao: 'Substitua y = 6 - x na primeira equação para resolver o sistema.',
    feedback: {
      mensagens: {
        acerto: 'Ótimo trabalho!',
        erro: 'Revise os passos da substituição.',
      },
    },
  },
  {
    id: 6,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\nx + 2y = 8\nx − y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 2', correta: true },
      { id: 'b', texto: 'x = 3, y = 3', correta: false },
      { id: 'c', texto: 'x = 5, y = 1', correta: false },
      { id: 'd', texto: 'x = 6, y = 0', correta: false },
    ],
    explicacao: 'Substitua x = y + 2 na primeira equação para encontrar os valores.',
    feedback: {
      mensagens: {
        acerto: 'Parabéns!',
        erro: 'Revise a substituição e refaça o cálculo.',
      },
    },
  },

  {
    id: 7,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n3x − y = 7\nx + y = 5',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 2', correta: true },
      { id: 'b', texto: 'x = 2, y = 3', correta: false },
      { id: 'c', texto: 'x = 4, y = 1', correta: false },
      { id: 'd', texto: 'x = 5, y = 0', correta: false },
    ],
    explicacao: 'Substitua y = 5 - x na primeira equação.',
    feedback: {
      mensagens: {
        acerto: 'Correto, bom trabalho!',
        erro: 'Reveja os passos e tente novamente.',
      },
    },
  },
  {
    id: 8,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\nx + 2y = 10\n2x − y = 7',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 4', correta: true },
      { id: 'b', texto: 'x = 4, y = 3', correta: false },
      { id: 'c', texto: 'x = 2, y = 5', correta: false },
      { id: 'd', texto: 'x = 5, y = 2', correta: false },
    ],
    explicacao: 'Substitua y = (10 - x)/2 na segunda equação.',
    feedback: {
      mensagens: {
        acerto: 'Você acertou!',
        erro: 'Tente fazer a substituição com atenção.',
      },
    },
  },
  {
    id: 9,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n4x + y = 11\nx − y = 3',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'facil',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 3', correta: false },
      { id: 'b', texto: 'x = 3, y = 2', correta: true },
      { id: 'c', texto: 'x = 4, y = 1', correta: false },
      { id: 'd', texto: 'x = 5, y = 0', correta: false },
    ],
    explicacao: 'Substitua y = 3 - x na primeira equação.',
    feedback: {
      mensagens: {
        acerto: 'Muito bem!',
        erro: 'Revise as substituições e tente novamente.',
      },
    },
  },
  // Exercícios Médio
  {
    id: 10,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n3x + 2y = 12\nx − y = 1',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 1', correta: false },
      { id: 'b', texto: 'x = 3, y = 2', correta: true },
      { id: 'c', texto: 'x = 4, y = 3', correta: false },
      { id: 'd', texto: 'x = 1, y = 4', correta: false },
    ],
    explicacao: 'Substitua y = x - 1 na primeira equação.',
    feedback: {
      mensagens: {
        acerto: 'Excelente trabalho!',
        erro: 'Reveja as operações matemáticas.',
      },
    },
  },
  {
    id: 11,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n5x − 2y = 6\n3x + 2y = 14',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 4', correta: true },
      { id: 'b', texto: 'x = 3, y = 3', correta: false },
      { id: 'c', texto: 'x = 1, y = 5', correta: false },
      { id: 'd', texto: 'x = 4, y = 2', correta: false },
    ],
    explicacao: 'Some as equações para eliminar y e resolver x.',
    feedback: {
      mensagens: {
        acerto: 'Ótimo trabalho!',
        erro: 'Certifique-se de somar corretamente.',
      },
    },
  },
  
  {
    id: 12,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n2x + 3y = 18\nx − y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 2', correta: false },
      { id: 'b', texto: 'x = 6, y = 4', correta: true },
      { id: 'c', texto: 'x = 5, y = 3', correta: false },
      { id: 'd', texto: 'x = 3, y = 1', correta: false },
    ],
    explicacao: 'Substitua y = x - 2 na primeira equação para encontrar x.',
    feedback: {
      mensagens: {
        acerto: 'Muito bom!',
        erro: 'Verifique sua substituição e tente novamente.',
      },
    },
  },
  {
    id: 13,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n4x − 3y = 8\n2x + 3y = 12',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 2', correta: true },
      { id: 'b', texto: 'x = 2, y = 3', correta: false },
      { id: 'c', texto: 'x = 4, y = 1', correta: false },
      { id: 'd', texto: 'x = 1, y = 4', correta: false },
    ],
    explicacao: 'Some as equações para eliminar y e resolver x.',
    feedback: {
      mensagens: {
        acerto: 'Ótimo trabalho!',
        erro: 'Reveja o somatório das equações.',
      },
    },
  },
  {
    id: 14,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n3x + 4y = 20\nx − y = 1',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 3', correta: true },
      { id: 'b', texto: 'x = 3, y = 4', correta: false },
      { id: 'c', texto: 'x = 5, y = 2', correta: false },
      { id: 'd', texto: 'x = 2, y = 5', correta: false },
    ],
    explicacao: 'Substitua y = x - 1 na primeira equação para resolver.',
    feedback: {
      mensagens: {
        acerto: 'Excelente!',
        erro: 'Confira suas substituições com atenção.',
      },
    },
  },
  {
    id: 15,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n5x + 2y = 20\n3x − 2y = 10',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 0', correta: true },
      { id: 'b', texto: 'x = 3, y = 2', correta: false },
      { id: 'c', texto: 'x = 5, y = 1', correta: false },
      { id: 'd', texto: 'x = 2, y = 3', correta: false },
    ],
    explicacao: 'Some as equações para eliminar y e encontrar x.',
    feedback: {
      mensagens: {
        acerto: 'Correto, bom trabalho!',
        erro: 'Revise a operação de soma entre as equações.',
      },
    },
  },

  {
    id: 16,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n2x + 3y − z = 5\nx − y + z = 4\n3x + y + z = 10',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 1, z = 3', correta: true },
      { id: 'b', texto: 'x = 3, y = 2, z = 1', correta: false },
      { id: 'c', texto: 'x = 1, y = 3, z = 2', correta: false },
      { id: 'd', texto: 'x = 2, y = 3, z = 1', correta: false },
    ],
    explicacao: 'Elimine uma variável por vez e resolva o sistema gradualmente.',
    feedback: {
      mensagens: {
        acerto: 'Muito bem! Você domina sistemas complexos!',
        erro: 'Tente resolver com cuidado para eliminar as variáveis.',
      },
    },
  },
  {
    id: 17,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n4x − y + z = 7\nx + 2y − z = 3\n2x + y + 2z = 8',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 1, y = 2, z = 1', correta: true },
      { id: 'b', texto: 'x = 2, y = 1, z = 3', correta: false },
      { id: 'c', texto: 'x = 3, y = 1, z = 2', correta: false },
      { id: 'd', texto: 'x = 1, y = 3, z = 2', correta: false },
    ],
    explicacao: 'Substitua as variáveis gradativamente até reduzir o sistema.',
    feedback: {
      mensagens: {
        acerto: 'Excelente trabalho!',
        erro: 'Revise as substituições e tente novamente.',
      },
    },
  },

  {
    id: 18,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n2x + y = 10\nx − y = 3',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 5, y = 0', correta: true },
      { id: 'b', texto: 'x = 4, y = 2', correta: false },
      { id: 'c', texto: 'x = 6, y = 1', correta: false },
      { id: 'd', texto: 'x = 3, y = 3', correta: false },
    ],
    explicacao: 'Substitua y = x - 3 na primeira equação para encontrar x.',
    feedback: {
      mensagens: {
        acerto: 'Ótimo trabalho!',
        erro: 'Revise a substituição e tente novamente.',
      },
    },
  },
  {
    id: 19,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n5x + 3y = 12\n2x − y = 4',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 2', correta: true },
      { id: 'b', texto: 'x = 3, y = 1', correta: false },
      { id: 'c', texto: 'x = 4, y = 0', correta: false },
      { id: 'd', texto: 'x = 5, y = -1', correta: false },
    ],
    explicacao: 'Use o método da adição para eliminar y.',
    feedback: {
      mensagens: {
        acerto: 'Você conseguiu!',
        erro: 'Revise o método da adição e tente novamente.',
      },
    },
  },
  {
    id: 20,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n4x + y = 15\nx − y = 1',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'medio',
    respostas: [
      { id: 'a', texto: 'x = 4, y = -1', correta: false },
      { id: 'b', texto: 'x = 4, y = 1', correta: true },
      { id: 'c', texto: 'x = 3, y = 3', correta: false },
      { id: 'd', texto: 'x = 2, y = 2', correta: false },
    ],
    explicacao: 'Substitua y = x - 1 na primeira equação para encontrar x.',
    feedback: {
      mensagens: {
        acerto: 'Parabéns, muito bem feito!',
        erro: 'Tente refazer os cálculos com atenção.',
      },
    },
  },
  {
    id: 21,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n2x − y = 3\n3x + y = 10',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 5', correta: true },
      { id: 'b', texto: 'x = 4, y = 1', correta: false },
      { id: 'c', texto: 'x = 3, y = 3', correta: false },
      { id: 'd', texto: 'x = 5, y = 0', correta: false },
    ],
    explicacao: 'Use o método da adição para eliminar y e resolver x.',
    feedback: {
      mensagens: {
        acerto: 'Muito bom, você acertou!',
        erro: 'Revise o método da adição.',
      },
    },
  },
  {
    id: 22,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n3x + 2y = 12\nx − y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 2', correta: true },
      { id: 'b', texto: 'x = 3, y = 3', correta: false },
      { id: 'c', texto: 'x = 5, y = 1', correta: false },
      { id: 'd', texto: 'x = 2, y = 4', correta: false },
    ],
    explicacao: 'Substitua y = x - 2 na primeira equação para resolver.',
    feedback: {
      mensagens: {
        acerto: 'Correto, ótimo trabalho!',
        erro: 'Revise sua substituição com calma.',
      },
    },
  },
  {
    id: 23,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n2x + 3y = 18\nx − y = 3',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 5, y = 2', correta: true },
      { id: 'b', texto: 'x = 4, y = 3', correta: false },
      { id: 'c', texto: 'x = 6, y = 1', correta: false },
      { id: 'd', texto: 'x = 2, y = 5', correta: false },
    ],
    explicacao: 'Resolva substituindo y = x - 3 na equação 2x + 3y = 18.',
    feedback: {
      mensagens: {
        acerto: 'Muito bom!',
        erro: 'Tente resolver com mais calma.',
      },
    },
  },
  {
    id: 24,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\nx + 2y = 8\nx − y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 2', correta: true },
      { id: 'b', texto: 'x = 3, y = 3', correta: false },
      { id: 'c', texto: 'x = 5, y = 1', correta: false },
      { id: 'd', texto: 'x = 2, y = 5', correta: false },
    ],
    explicacao: 'Substitua y = x - 2 para resolver as equações.',
    feedback: {
      mensagens: {
        acerto: 'Excelente!',
        erro: 'Confira sua substituição com atenção.',
      },
    },
  },
  
  {
    id: 25,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n5x + 3y = 12\n2x - y = 4',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 2, y = 2', correta: true },
      { id: 'b', texto: 'x = 4, y = 1', correta: false },
      { id: 'c', texto: 'x = 3, y = 3', correta: false },
      { id: 'd', texto: 'x = 5, y = 0', correta: false },
    ],
    explicacao: 'Substitua y = 2x - 4 na equação 5x + 3y = 12 e resolva para x.',
    feedback: {
      mensagens: {
        acerto: 'Muito bem, você acertou!',
        erro: 'Tente novamente com calma.',
      },
    },
  },
  {
    id: 26,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n3x + y = 9\n2x − y = 4',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 1', correta: true },
      { id: 'b', texto: 'x = 4, y = 0', correta: false },
      { id: 'c', texto: 'x = 2, y = 3', correta: false },
      { id: 'd', texto: 'x = 1, y = 2', correta: false },
    ],
    explicacao: 'Elimine y somando as equações e resolvendo para x.',
    feedback: {
      mensagens: {
        acerto: 'Excelente trabalho!',
        erro: 'Revise a soma das equações.',
      },
    },
  },
  {
    id: 27,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n4x + 3y = 12\nx - y = 2',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 2', correta: true },
      { id: 'b', texto: 'x = 4, y = 1', correta: false },
      { id: 'c', texto: 'x = 2, y = 5', correta: false },
      { id: 'd', texto: 'x = 4, y = 3', correta: false },
    ],
    explicacao: 'Isolando y da segunda equação e substituindo na primeira, você encontra x.',
    feedback: {
      mensagens: {
        acerto: 'Você está indo muito bem!',
        erro: 'Confira os cálculos e tente novamente.',
      },
    },
  },
  {
    id: 28,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\nx − y = 1\n2x + y = 7',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 2', correta: true },
      { id: 'b', texto: 'x = 5, y = 1', correta: false },
      { id: 'c', texto: 'x = 4, y = 2', correta: false },
      { id: 'd', texto: 'x = 6, y = 1', correta: false },
    ],
    explicacao: 'Substitua y = x - 1 na equação 2x + y = 7 e resolva.',
    feedback: {
      mensagens: {
        acerto: 'Correto, parabéns!',
        erro: 'Revise a substituição e resolva novamente.',
      },
    },
  },
  {
    id: 29,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da substituição:\n3x + y = 5\nx + y = 7',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 3, y = 2', correta: true },
      { id: 'b', texto: 'x = 4, y = 1', correta: false },
      { id: 'c', texto: 'x = 2, y = 3', correta: false },
      { id: 'd', texto: 'x = 5, y = 0', correta: false },
    ],
    explicacao: 'Substitua y = 7 - x na equação 3x + y = 5 e resolva.',
    feedback: {
      mensagens: {
        acerto: 'Muito bom!',
        erro: 'Revise a substituição para encontrar a solução correta.',
      },
    },
  },
  {
    id: 30,
    videoAulaID: [],
    trancado: false,
    feito: false,
    acertou: false,
    pergunta: 'Resolva o sistema pelo método da adição:\n5x − 2y = 10\nx + y = 6',
    imagem: '',
    tipo: 'múltipla escolha',
    nivel_dificuldade: 'dificil',
    respostas: [
      { id: 'a', texto: 'x = 4, y = 2', correta: true },
      { id: 'b', texto: 'x = 3, y = 3', correta: false },
      { id: 'c', texto: 'x = 5, y = 1', correta: false },
      { id: 'd', texto: 'x = 2, y = 5', correta: false },
    ],
    explicacao: 'Some as equações para eliminar y e encontrar x.',
    feedback: {
      mensagens: {
        acerto: 'Parabéns, você concluiu todos os exercícios!',
        erro: 'Revise os passos para resolver este sistema.',
      },
    },
  },
];



